In [1]:
# Analytical Solution
# Eq. 2 in Meyer's 2010 paper 
# meV units
# Calculation section

import numpy as np

def Krat_Meyer2010_eq2(nu, J, D):
    a = 0.8*10**-9 #in m
    m = 0.7*9.109*10**-31 #in kg
    hbar = 6.626*10**-34/(2*np.pi) #in J*s
    Const = (2*m*a**2/hbar**2) # in J^-1
    ConsteV = Const*(1.6*10**-19)/1000 # in meV^-1
    Krat_E_an = -ConsteV*D**2/((nu + 1/2) + np.sqrt((J + 1/2)**2 + ConsteV*D))**2 # in meV
    return Krat_E_an  


D = [19.1, 16.0, 15.8, 15.0, 13.0] # in meV

Erel = [0]*5
for i in range(5): # number of D 
    for j in range(8): # number of energy levels for each D minus 1
        Erel[i] = np.append(Erel[i], [0]) # creating a position for each eigenvalue
    Erel[i] = [float(x) for x in Erel[i]] 
Erel = np.array(Erel)

Eabs = [0]*5
for i in range(5): # number of D 
    for j in range(8): # number of energy levels for each D minus 1
        Eabs[i] = np.append(Eabs[i], [0]) # creating a position for each eigenvalue
    Eabs[i] = [float(x) for x in Eabs[i]]    
Eabs = np.array(Eabs)

               
for i in range(5): 
    count = 0
    for nu in range(3):
        for J in range(3): # in meV
            Erel[i][count] = round(Krat_Meyer2010_eq2(nu, J, D[i]) - Krat_Meyer2010_eq2(0, 0, D[i]), 5)
            Eabs[i][count] = round(Krat_Meyer2010_eq2(nu, J, D[i]), 5)
            count += 1

print(Erel)
print('')
print(Eabs)
            

[[0.      2.0349  2.56958 2.1375  2.57812 2.76987 2.61044 2.77352 2.8634 ]
 [0.      1.51993 1.90151 1.58409 1.90661 2.04294 1.92665 2.04512 2.10889]
 [0.      1.48832 1.86083 1.55036 1.86575 1.9988  1.88511 2.0009  2.06314]
 [0.      1.36405 1.70126 1.41802 1.70549 1.82582 1.7223  1.82762 1.88388]
 [0.      1.0695  1.32559 1.10615 1.32837 1.41952 1.33972 1.42071 1.46327]]

[[-3.03175 -0.99685 -0.46217 -0.89425 -0.45363 -0.26188 -0.42131 -0.25822
  -0.16834]
 [-2.22736 -0.70743 -0.32585 -0.64327 -0.32075 -0.18442 -0.30071 -0.18224
  -0.11847]
 [-2.17868 -0.69036 -0.31785 -0.62832 -0.31293 -0.17988 -0.29357 -0.17778
  -0.11555]
 [-1.9881  -0.62404 -0.28683 -0.57008 -0.2826  -0.16228 -0.2658  -0.16047
  -0.10422]
 [-1.54169 -0.47219 -0.2161  -0.43554 -0.21332 -0.12217 -0.20197 -0.12098
  -0.07842]]


In [4]:
# plot the table
# run previous section
import plotly.graph_objects as go
import numpy as np

Eabs_paper = [[3.3567, 3.36574, 3.35927, 3.35884, 3.35928, '', 3.35931, '', ''], 
              [3.3598, 3.36132, 3.36170, 3.36138, 3.36171, '', 3.36173, '', ''], 
              [3.3600, 3.36149, 3.36186, 3.36155, 3.36187, '', 3.36189, '', ''], 
              [3.3608, 3.36212, 3.36244, 3.36217, 3.36245, '', 3.36246, '', ''],
              [3.3628, 3.36386, 3.36411, 3.36389, 3.36411, '', 3.36412, '', '']]

Erel_paper = [[0, 2.04, 2.57, 2.14, 2.58, '', 2.61, '', ''], 
             [0, 1.52, 1.90, 1.58, 1.91, '', 1.93, '', ''], 
             [0, 1.49, 1.86, 1.55, 1.87, '', 1.89, '', ''],
             [0, 1.32, 1.64, 1.37, 1.65, '', 1.66, '', ''], 
             [0, 1.06, 1.31, 1.09, 1.31, '', 1.32, '', '']]

Exciton = ['I9', 'I8', 'I7', 'I6', 'I4']
D = [19.1, 16.0, 15.8, 15.0, 13.0]              
for i in range(5):
    print('Exciton: ', Exciton[i], ' Binding Energy: ', D[i], ' meV')
    fig = go.Figure(data=[go.Table(header=dict(values=['nu', 'J', 'Quoted Absolute Excited State Energy (eV)', 'Replication Absolute Excited State Energy (meV)', 
                                                   'Quoted Relative Energy Above Ground State (meV)','Replicated Relative Energy Above Ground State  (meV)']),
                 cells=dict(values=[['0', '', '', '1', '', '', '2', '', ''],
                                    ['0', '1' ,'2' , '0','1' ,'2' , '0','1' ,'2'],
                                    Eabs_paper[i], Eabs[i], Erel_paper[i], Erel[i]]))])
    fig.show()



Exciton:  I9  Binding Energy:  19.1  meV


Exciton:  I8  Binding Energy:  16.0  meV


Exciton:  I7  Binding Energy:  15.8  meV


Exciton:  I6  Binding Energy:  15.0  meV


Exciton:  I4  Binding Energy:  13.0  meV
