In [14]:
# Analytical Solution
# Eq. 3 in Meyer's 2010 paper 
# eV units

import numpy as np

def Krat_Meyer2010_eq3(n, l, RD):
    s = 1.0136
    t = 1.337
    a = 0.775
    mh = 0.59 
    me = 0.24 
    Eg = 3.37 # eV 
    #Krat_E_an = 2*RD*( - s**2*t**2/2*mh/me*(n + 1/2 + np.sqrt((l + 1/2)**2 + s*t**2/a*mh/me))**(-2))
    Krat_E_an = Eg + 2*RD*(a**2 - 11/8*a - s**2*t**2/2*mh/me*(n + 1/2 + np.sqrt((l + 1/2)**2 + s*t**2/a*mh/me))**(-2))
    return Krat_E_an

ED = [0.0558, 0.0537, 0.05355, 0.053, 0.0516] # in eV

Erel = [0]*5
for i in range(5): # number of ED 
    for j in range(8): # number of energy levels for each ED minus 1
        Erel[i] = np.append(Erel[i], [0]) # creating a position for each eigenvalue
    Erel[i] = [float(x) for x in Erel[i]] 
Erel = np.array(Erel)

Eabs = [0]*5
for i in range(5): # number of ED 
    for j in range(8): # number of energy levels for each ED minus 1
        Eabs[i] = np.append(Eabs[i], [0]) # creating a position for each eigenvalue
    Eabs[i] = [float(x) for x in Eabs[i]]    
Eabs = np.array(Eabs)

               
for i in range(5): 
    count = 0
    for nu in range(3):
        for J in range(3):
            Erel[i][count] = round((Krat_Meyer2010_eq3(nu, J, ED[i]) - Krat_Meyer2010_eq3(0, 0, ED[i]))*1000, 4)  # in meV
            Eabs[i][count] = round(Krat_Meyer2010_eq3(nu, J, ED[i]), 4)  # in eV
            count += 1

print(Erel)
print('')
print(Eabs)
            

[[ 0.      6.2227 12.9343 12.8141 15.5197 18.7443 18.6832 20.0946 21.8858]
 [ 0.      5.9885 12.4475 12.3319 14.9356 18.0389 17.9801 19.3383 21.0622]
 [ 0.      5.9717 12.4128 12.2974 14.8939 17.9885 17.9298 19.2843 21.0034]
 [ 0.      5.9104 12.2853 12.1711 14.7409 17.8037 17.7457 19.0862 20.7876]
 [ 0.      5.7543 11.9608 11.8496 14.3516 17.3335 17.2769 18.5821 20.2385]]

[[3.2891 3.2954 3.3021 3.302  3.3047 3.3079 3.3078 3.3092 3.311 ]
 [3.2922 3.2982 3.3046 3.3045 3.3071 3.3102 3.3102 3.3115 3.3132]
 [3.2924 3.2984 3.3048 3.3047 3.3073 3.3104 3.3103 3.3117 3.3134]
 [3.2932 3.2991 3.3055 3.3054 3.3079 3.311  3.3109 3.3123 3.314 ]
 [3.2952 3.301  3.3072 3.3071 3.3096 3.3126 3.3125 3.3138 3.3155]]


In [15]:
# plot the table
# run previous section
import plotly.graph_objects as go
import numpy as np

Eabs_paper = [[3.3567, 3.3629, 3.3697, 3.3696, 3.3723, '', 3.3754, '', ''], 
              [3.3598, 3.3658, 3.3722, 3.3721, 3.36747, '', 3.3778, '', ''], 
              [3.3600, 3.3660, 3.3724, 3.3723, 3.3749, '', 3.3779, '', ''], 
              [3.3608, 3.3667, 3.3731, 3.3729, 3.3755, '', 3.3785, '', ''],
              [3.3628, 3.3686, 3.3748, 3.3747, 3.3772, '', 3.3801, '', '']]

Erel_paper = [[0, 6.2, 13.0, 12.9, 15.6, '', 18.7, '', ''], 
             [0, 6.0, 12.4, 12.3, 14.9, '', 18.0, '', ''], 
             [0, 6.0, 12.4, 12.3, 14.9, '', 17.9, '', ''],
             [0, 5.9, 12.4, 12.1, 14.7, '', 17.7, '', ''], 
             [0, 5.8, 12.0, 11.9, 14.4, '', 17.3, '', '']]

Exciton = ['I9', 'I8', 'I7', 'I6', 'I4']
ED = [55.8, 53.7, 53.55, 53.0, 51.6] # in meV             
for i in range(5):
    print('Exciton: ', Exciton[i], ' Binding Energy: ', ED[i], ' meV')
    fig = go.Figure(data=[go.Table(header=dict(values=['nu', 'J', 'Quoted Absolute Excited State Energy (eV)', 'Replication Absolute Excited State Energy (eV)', 
                                                   'Quoted Relative Energy Above Ground State (meV)','Replicated Relative Energy Above Ground State  (meV)']),
                 cells=dict(values=[['0', '', '', '1', '', '', '2', '', ''],
                                    ['0', '1' ,'2' , '0','1' ,'2' , '0','1' ,'2'],
                                    Eabs_paper[i], Eabs[i], Erel_paper[i], Erel[i]]))])
    fig.show()

Exciton:  I9  Binding Energy:  55.8  meV


Exciton:  I8  Binding Energy:  53.7  meV


Exciton:  I7  Binding Energy:  53.55  meV


Exciton:  I6  Binding Energy:  53.0  meV


Exciton:  I4  Binding Energy:  51.6  meV
